graph LR
    A[Usuario Waze] --> B[Alertas]
    B --> C[Base de Datos Waze]
    C --> API[API Waze Cities]
    SERVER[Servidor] --> API
    SERVER --> SQL[Bases de Datos SQL]
    SQL --> DASH[Dash]
    AF[Airflow] --> SERVER
    SERVER --> ML[MLFlow]
    ML --> DASH
    DASH --> E[Dashboard]
    U[Usuario Dashboard] --> E
    E --> DASH
    DASH --> SERVER
